name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12.x', '12.16.1' ]
    name: Node ${{ matrix.node }}
    steps:
    - uses: actions/checkout@v2
    - run: |
        git remote set-branches --add origin master
        git fetch
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Cache NPM Dependencies
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install Dependencies
      run: npm ci
      env:
        NODE_ENV: development
    - name: Unit Tests
      run: npm run test:lint && npm run test:unit && npm run test:danger && npm run test:git-history
      env:
        NODE_ENV: production
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Docker version
      run: docker-compose --version
    - name: Integration tests
      run: |
        bash ./scripts/run-integration-tests.travis.sh -x
      env:
        NODE_ENV: production
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HEROKU_DOCKER_USERNAME: ${{ secrets.HEROKU_DOCKER_USERNAME }}
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
        SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
